name: Bug Report
description: File a Bug Report
title: "[Bug] CHANGE TITLE"
labels: [ "🐞 Bug" ]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? Describe in detail down below and include the mod version as well.
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: loaders
    attributes:
      label: What mod loaders is this problem occuring on?
      description: Please select all that apply.
      multiple: true
      options:
        - Fabric
        - Forge
        - Neoforge
        - Quilt
    validations:
      required: true
  - type: checkboxes
    id: types
    attributes:
      label: What do you think this bug is related to?
      description: Please select all that apply.
      options:
        - label: Visual
        - label: Feature Related
        - label: Crash
        - label: Mod Conflict
        - label: Others
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please paste any crash logs or latest.logs down below.
      placeholder: You can look into `.minecraft/logs` and find the `latest.log`. You can use https://mclo.gs/ or just drag and drop the log file down below.
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? A Video? Anything that will give us more context/information about the issue you are encountering!

        Tip: You can attach images/videos under 10 MB or other log files by clicking this area to highlight it and then dragging files in.
  - type: markdown
    attributes:
      value: |
        Before submitting a bug report, please make sure that this issue isn't a duplicate issue. You can use the search feature to find existing issues.

        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: updates
    attributes:
      label: By submitting this issue, I have confirmed I have followed all instructions and all my mods are up-to-date.
      options:
        - label: 'Yes'
          required: true
