name: Feature Request
description: Suggest a change or addition to the project!
title: "[Feature] CHANGE TITLE"
labels: [ "✨ Enhancement" ]
body:
  - type: textarea
    attributes:
      label: What is your feature request?
      description: |
        Please describe the feature or change you would like to see. Be descriptive!

        Tip: You can attach images/videos by clicking this area to highlight it and then dragging files in.
  - type: checkboxes
    id: types
    attributes:
      label: What type of change is this?
      description: Please select all that apply.
      options:
        - label: Visual
        - label: Features/Mechanics
        - label: Performance
        - label: Compat
        - label: Others
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!